function createFigureDesign(time, YSI, GIR)
%CREATEFIGURE(time, YSI, GIR)

%  Auto-generated by MATLAB on 26-Aug-2015 19:14:43

YSI(YSI == 0) = nan;
timelim = [min(time) max(time)];

% Create figure
figure1 = figure;

% Create axes2
axes2 = axes('Parent',figure1);
hold(axes2,'on');

ylabel(axes2,'20% dextrose infusion rate','FontSize',20);

box(axes2,'on');
xlim(axes2,timelim);
ylim(axes2,[0 100]);
set(axes2,'FontSize',14,'YAxisLocation','right');

% Create axes1
axes1 = axes('Parent',figure1);
hold(axes1,'on');

xlabel('time (min)','FontSize',20);
ylabel('arterial plasma glucose (mg/dL)','FontSize',20);

box(axes1,'on');
xlim(axes1,timelim);
set(axes1,'FontSize',14);

% Plot

plot(time,GIR,'DisplayName','dextrose','MarkerFaceColor',[1 0 0],'MarkerEdgeColor',[1 0 0],'Color',[0 0 0]);
plot(time,YSI,'DisplayName','glucose','MarkerFaceColor',[1 1 1],'MarkerEdgeColor',[0 0 0],'MarkerSize',8,'Marker','o','LineStyle','none', ...
    'Color',[0.501960813999176 0.501960813999176 0.501960813999176]);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[1 1 1]);